# Generated by Django 2.1 on 2018-08-17 12:39

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180809_0613'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 10800)),
        ),
    ]
