# Generated by Django 2.1 on 2018-08-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='super_admin',
        ),
        migrations.RemoveField(
            model_name='course',
            name='super_admin',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='test',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='course',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='super_admin',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='test',
            name='course',
        ),
        migrations.RemoveField(
            model_name='test',
            name='super_admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='super_admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='type_of_user',
            field=models.CharField(choices=[('user', 'User'), ('superadmin', 'Super Admin')], max_length=11),
        ),
        migrations.DeleteModel(
            name='Centre',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
