# Generated by Django 2.1 on 2018-08-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_steem_posting_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='cover',
            field=models.ImageField(null=True, upload_to='song_covers/'),
        ),
    ]
